### ISSUE TITLE
preflight ignores rules added with @layer 

### ISSUE THREAD

**Issue by wheeOs** [Roman86/tailwindcss-scoped-preflight#62]
**Describe the bug**
First of all, I'm not sure if this is a bug or if scoped preflight is supposed to also affect those rules, but at least I was surprised that they are unaffected in my experience. 
As you know tailwind is injecting the rules which were added by e.g. `@layer components` when you use `@tailwind components;`. Isn't it intuitive to expect those to get processed by scoped preflight as well?

**To Reproduce**
write a root .css containing:
```css
@tailwind base;

@layer base {
  body {
    color: red;
  }
}
```

use the scopedPreflight plugin in tailwind.config.js:
```js
...
scopedPreflightStyles({
	isolationStrategy: isolateInsideOfContainer("#bar")
}) 
...
```

run the app which imports the root .css

**Expected behaviour**
the produced css contains the following (besides the already included base rules):
```css
body:where(#bar,#bar *){color:red;}
```
